=== TheIRGurus/Apps/fn_artifact_utils/payload_samples/artifact_utils_add_tags/output_json_schema.json
{
  "$schema": "http://json-schema.org/draft-06/schema",
  "type": "object",
  "properties": {
    "version": {
      "type": "number"
    },
    "success": {
      "type": "boolean"
    },
    "reason": {},
    "content": {
      "type": "object",
      "properties": {
        "537": {
          "type": "object",
          "properties": {
            "id": {
              "type": "integer"
            },
            "type": {
              "type": "integer"
            },
            "value": {
              "type": "string"
            },
            "description": {},
            "summary": {},
            "creator": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "integer"
                },
                "type": {
                  "type": "string"
                },
                "name": {
                  "type": "string"
                },
                "display_name": {
                  "type": "string"
                }
              }
            },
            "created": {
              "type": "integer"
            },
            "last_modified_by": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "integer"
                },
                "type": {
                  "type": "string"
                },
                "name": {
                  "type": "string"
                },
                "display_name": {
                  "type": "string"
                }
              }
            },
            "last_modified_time": {
              "type": "integer"
            },
            "related_incident_count": {
              "type": "integer"
            },
            "last_related_inc_id": {
              "type": "integer"
            },
            "last_related_inc_owner_handle": {
              "type": "integer"
            },
            "first_related_inc_id": {
              "type": "integer"
            },
            "first_related_inc_owner_handle": {
              "type": "integer"
            },
            "perms": {
              "type": "object",
              "properties": {
                "write": {
                  "type": "boolean"
                }
              }
            },
            "first_associated_time": {
              "type": "integer"
            },
            "last_associated_time": {
              "type": "integer"
            },
            "properties": {},
            "tags": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "tag_handle": {
                    "type": "integer"
                  },
                  "value": {}
                }
              }
            },
            "version": {
              "type": "integer"
            },
            "scan_option": {
              "type": "string"
            },
            "relating_incidents": {
              "type": "boolean"
            },
            "hit_threat_sources": {
              "type": "array"
            },
            "relating": {
              "type": "boolean"
            },
            "last_scan_hits": {
              "type": "array"
            }
          }
        },
        "542": {
          "type": "object",
          "properties": {
            "id": {
              "type": "integer"
            },
            "type": {
              "type": "integer"
            },
            "value": {
              "type": "string"
            },
            "description": {},
            "summary": {},
            "creator": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "integer"
                },
                "type": {
                  "type": "string"
                },
                "name": {
                  "type": "string"
                },
                "display_name": {
                  "type": "string"
                }
              }
            },
            "created": {
              "type": "integer"
            },
            "last_modified_by": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "integer"
                },
                "type": {
                  "type": "string"
                },
                "name": {
                  "type": "string"
                },
                "display_name": {
                  "type": "string"
                }
              }
            },
            "last_modified_time": {
              "type": "integer"
            },
            "related_incident_count": {
              "type": "integer"
            },
            "last_related_inc_id": {
              "type": "integer"
            },
            "last_related_inc_owner_handle": {
              "type": "integer"
            },
            "first_related_inc_id": {
              "type": "integer"
            },
            "first_related_inc_owner_handle": {
              "type": "integer"
            },
            "perms": {
              "type": "object",
              "properties": {
                "write": {
                  "type": "boolean"
                }
              }
            },
            "first_associated_time": {
              "type": "integer"
            },
            "last_associated_time": {
              "type": "integer"
            },
            "properties": {},
            "tags": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "tag_handle": {
                    "type": "integer"
                  },
                  "value": {}
                }
              }
            },
            "version": {
              "type": "integer"
            },
            "scan_option": {
              "type": "string"
            },
            "relating_incidents": {
              "type": "boolean"
            },
            "hit_threat_sources": {
              "type": "array"
            },
            "relating": {
              "type": "boolean"
            },
            "last_scan_hits": {
              "type": "array"
            }
          }
        },
        "543": {
          "type": "object",
          "properties": {
            "id": {
              "type": "integer"
            },
            "type": {
              "type": "integer"
            },
            "value": {
              "type": "string"
            },
            "description": {},
            "summary": {},
            "creator": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "integer"
                },
                "type": {
                  "type": "string"
                },
                "name": {
                  "type": "string"
                },
                "display_name": {
                  "type": "string"
                }
              }
            },
            "created": {
              "type": "integer"
            },
            "last_modified_by": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "integer"
                },
                "type": {
                  "type": "string"
                },
                "name": {
                  "type": "string"
                },
                "display_name": {
                  "type": "string"
                }
              }
            },
            "last_modified_time": {
              "type": "integer"
            },
            "related_incident_count": {
              "type": "integer"
            },
            "last_related_inc_id": {
              "type": "integer"
            },
            "last_related_inc_owner_handle": {
              "type": "integer"
            },
            "first_related_inc_id": {
              "type": "integer"
            },
            "first_related_inc_owner_handle": {
              "type": "integer"
            },
            "perms": {
              "type": "object",
              "properties": {
                "write": {
                  "type": "boolean"
                }
              }
            },
            "first_associated_time": {
              "type": "integer"
            },
            "last_associated_time": {
              "type": "integer"
            },
            "properties": {},
            "tags": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "tag_handle": {
                    "type": "integer"
                  },
                  "value": {}
                }
              }
            },
            "version": {
              "type": "integer"
            },
            "scan_option": {
              "type": "string"
            },
            "relating_incidents": {
              "type": "boolean"
            },
            "hit_threat_sources": {
              "type": "array"
            },
            "relating": {
              "type": "boolean"
            },
            "last_scan_hits": {
              "type": "array"
            }
          }
        }
      }
    },
    "raw": {},
    "inputs": {
      "type": "object",
      "properties": {
        "artifact_tag_values": {
          "type": "string"
        },
        "incident_id": {
          "type": "integer"
        },
        "artifact_id_list": {
          "type": "string"
        }
      }
    },
    "metrics": {
      "type": "object",
      "properties": {
        "version": {
          "type": "string"
        },
        "package": {
          "type": "string"
        },
        "package_version": {
          "type": "string"
        },
        "host": {
          "type": "string"
        },
        "execution_time_ms": {
          "type": "integer"
        },
        "timestamp": {
          "type": "string"
        }
      }
    }
  }
}

=== TheIRGurus/Apps/fn_artifact_utils/payload_samples/artifact_utils_remove_tags/output_json_example.json
{
  "version": 2.0,
  "success": true,
  "reason": null,
  "content": {
    "542": {
      "id": 542,
      "type": 1,
      "value": "10.156.54.204",
      "description": null,
      "summary": null,
      "creator": {
        "id": 1,
        "type": "user",
        "name": "john_doe@company.com",
        "display_name": "John Doe"
      },
      "created": 1683873651813,
      "last_modified_by": {
        "id": 49,
        "type": "apikey",
        "name": "6bf8c47e-77a6-41ad-ad22-1004f7eee7cb",
        "display_name": "AppBuilder"
      },
      "last_modified_time": 1683874646685,
      "related_incident_count": 1,
      "last_related_inc_id": 2325,
      "last_related_inc_owner_handle": 33,
      "first_related_inc_id": 2325,
      "first_related_inc_owner_handle": 33,
      "perms": {
        "write": true
      },
      "first_associated_time": 1683873651813,
      "last_associated_time": 1683873651813,
      "properties": null,
      "tags": [
        {
          "tag_handle": 134,
          "value": null
        }
      ],
      "version": 2,
      "scan_option": "on",
      "relating_incidents": true,
      "hit_threat_sources": [],
      "relating": true,
      "last_scan_hits": []
    },
    "543": {
      "id": 543,
      "type": 1,
      "value": "10.16.157.4",
      "description": null,
      "summary": null,
      "creator": {
        "id": 1,
        "type": "user",
        "name": "john_doe@company.com",
        "display_name": "John Doe"
      },
      "created": 1683873651839,
      "last_modified_by": {
        "id": 49,
        "type": "apikey",
        "name": "6bf8c47e-77a6-41ad-ad22-1004f7eee7cb",
        "display_name": "AppBuilder"
      },
      "last_modified_time": 1683874648355,
      "related_incident_count": 1,
      "last_related_inc_id": 2325,
      "last_related_inc_owner_handle": 33,
      "first_related_inc_id": 2325,
      "first_related_inc_owner_handle": 33,
      "perms": {
        "write": true
      },
      "first_associated_time": 1683873651839,
      "last_associated_time": 1683873651839,
      "properties": null,
      "tags": [
        {
          "tag_handle": 134,
          "value": null
        }
      ],
      "version": 2,
      "scan_option": "on",
      "relating_incidents": true,
      "hit_threat_sources": [],
      "relating": true,
      "last_scan_hits": []
    }
  },
  "raw": null,
  "inputs": {
    "artifact_tag_values": "Malicious",
    "incident_id": 2325,
    "artifact_id_list": "1538,1539"
  },
  "metrics": {
    "version": "1.0",
    "package": "fn-artifact-utils",
    "package_version": "1.0.0",
    "host": "IBM-PF36KPAV",
    "execution_time_ms": 3654,
    "timestamp": "2023-05-12 02:57:28"
  }
}

=== TheIRGurus/Apps/fn_relations/payload_samples/relations_sync_datatable_data/output_json_example.json
{
  "version": 2.0,
  "success": true,
  "reason": null,
  "content": {
    "datatables": [
      "ldap_users"
    ],
    "rows": null,
    "incidents": [
      2797,
      2796,
      2798
    ]
  },
  "raw": null,
  "inputs": {
    "relations_datatables": "ldap_users",
    "incident_id": 2795,
    "relations_exclude_datatables": "dt_relations_child_incidents"
  },
  "metrics": {
    "version": "1.0",
    "package": "fn-relations",
    "package_version": "2.0.0",
    "host": "IBM-PF36KPAV",
    "execution_time_ms": 5321,
    "timestamp": "2023-08-30 23:41:19"
  }
}

=== TheIRGurus/Apps/fn_relations/payload_samples/relations_sync_artifact/output_json_example.json
{
  "version": 2.0,
  "success": true,
  "reason": null,
  "content": {
    "artifact": {
      "type": "String",
      "value": "windowsvmos2",
      "description": "Artifact Synced from incident 2795. created from Sentinel entity: cb1a7e68-4ff3-9aef-4224-e2b3b5adbdbc"
    },
    "incidents": [
      2797,
      2796,
      2798
    ]
  },
  "raw": null,
  "inputs": {
    "incident_id": 2795,
    "artifact_id": 3805
  },
  "metrics": {
    "version": "1.0",
    "package": "fn-relations",
    "package_version": "2.0.0",
    "host": "IBM-PF36KPAV",
    "execution_time_ms": 5944,
    "timestamp": "2023-08-30 23:27:26"
  }
}

=== TheIRGurus/Apps/fn_relations/payload_samples/relations_sync_task_notes/output_json_example.json
{
  "version": 2.0,
  "success": true,
  "reason": null,
  "content": {
    "new_note": {
      "text": {
        "format": "html",
        "content": "Response from Child Incident: <a href=\"#incidents/2796\" target=\"_blank\">2796</a><br>Task: <a href=\"#incidents/2796?taskId=617&tabName=comments\" target=\"_blank\">Task 615 from Parent: New Task for the Kids</a><br>Note ID: 413<br>On Date: 08/30/2023 23:31:03<br>By: John Doe<br><br><div class=\"rte\"><div>Sure looks like you can!</div></div>"
      },
      "parent_id": "409"
    }
  },
  "raw": null,
  "inputs": {
    "relations_note_id": 413,
    "task_id": 617
  },
  "metrics": {
    "version": "1.0",
    "package": "fn-relations",
    "package_version": "2.0.0",
    "host": "IBM-PF36KPAV",
    "execution_time_ms": 4242,
    "timestamp": "2023-08-30 23:31:10"
  }
}

=== TheIRGurus/Apps/fn_relations/payload_samples/relations_copy_task/output_json_example.json
{
  "version": 2.0,
  "success": true,
  "reason": null,
  "content": {
    "task": {
      "name": "Task 615 from Parent: New Task for the Kids",
      "due_date": 1693454400000,
      "phase_id": "Containment & Remediation",
      "required": true,
      "instructions": "<div class=\"rte\"><div>This is a instruction list for the new task!</div></div>"
    },
    "children": [
      2797,
      2796,
      2798
    ]
  },
  "raw": null,
  "inputs": {
    "task_id": 615,
    "relations_parent_incident_id": 2795
  },
  "metrics": {
    "version": "1.0",
    "package": "fn-relations",
    "package_version": "2.0.0",
    "host": "IBM-PF36KPAV",
    "execution_time_ms": 7216,
    "timestamp": "2023-08-30 23:29:46"
  }
}
