=== TheIRGurus/Apps/fn_artifact_utils/payload_samples/artifact_utils_delete_artifacts/output_json_schema.json
{
  "$schema": "http://json-schema.org/draft-06/schema",
  "type": "object",
  "properties": {
    "version": {
      "type": "number"
    },
    "success": {
      "type": "boolean"
    },
    "reason": {},
    "content": {
      "type": "object",
      "properties": {
        "incident_artifact_deletion": {
          "type": "object",
          "properties": {
            "success": {
              "type": "boolean"
            },
            "title": {},
            "message": {},
            "hints": {
              "type": "array"
            }
          }
        },
        "global_artifact_deletion": {
          "type": "object",
          "properties": {
            "success": {
              "type": "boolean"
            },
            "title": {},
            "message": {},
            "hints": {
              "type": "array"
            }
          }
        }
      }
    },
    "raw": {},
    "inputs": {
      "type": "object",
      "properties": {
        "incident_id": {
          "type": "integer"
        },
        "artifact_id_list": {
          "type": "string"
        },
        "artifact_remove_globally": {
          "type": "boolean"
        }
      }
    },
    "metrics": {
      "type": "object",
      "properties": {
        "version": {
          "type": "string"
        },
        "package": {
          "type": "string"
        },
        "package_version": {
          "type": "string"
        },
        "host": {
          "type": "string"
        },
        "execution_time_ms": {
          "type": "integer"
        },
        "timestamp": {
          "type": "string"
        }
      }
    }
  }
}

=== TheIRGurus/Apps/fn_artifact_utils/payload_samples/artifact_utils_delete_artifacts/output_json_example.json
{
  "version": 2.0,
  "success": true,
  "reason": null,
  "content": {
    "incident_artifact_deletion": {
      "success": true,
      "title": null,
      "message": null,
      "hints": []
    },
    "global_artifact_deletion": {
      "success": true,
      "title": null,
      "message": null,
      "hints": []
    }
  },
  "raw": null,
  "inputs": {
    "incident_id": 2325,
    "artifact_id_list": "1542",
    "artifact_remove_globally": true
  },
  "metrics": {
    "version": "1.0",
    "package": "fn-artifact-utils",
    "package_version": "1.0.0",
    "host": "IBM-PF36KPAV",
    "execution_time_ms": 2354,
    "timestamp": "2023-05-12 02:54:39"
  }
}
