=== TheIRGurus/Apps/fn_artifact_utils/payload_samples/artifact_utils_search_artifacts/output_json_schema.json
{
  "$schema": "http://json-schema.org/draft-06/schema",
  "type": "object",
  "properties": {
    "version": {
      "type": "number"
    },
    "success": {
      "type": "boolean"
    },
    "reason": {},
    "content": {
      "type": "object",
      "properties": {
        "recordsTotal": {
          "type": "integer"
        },
        "recordsFiltered": {
          "type": "integer"
        },
        "data": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "id": {
                "type": "integer"
              },
              "type": {
                "type": "string"
              },
              "value": {
                "type": "string"
              },
              "description": {},
              "attachment": {},
              "parent_id": {},
              "creator": {
                "type": "object",
                "properties": {
                  "id": {
                    "type": "integer"
                  },
                  "fname": {
                    "type": "string"
                  },
                  "lname": {
                    "type": "string"
                  },
                  "display_name": {
                    "type": "string"
                  },
                  "status": {
                    "type": "string"
                  },
                  "email": {
                    "type": "string"
                  },
                  "locked": {
                    "type": "boolean"
                  },
                  "password_changed": {
                    "type": "boolean"
                  },
                  "is_external": {
                    "type": "boolean"
                  },
                  "ui_theme": {
                    "type": "string"
                  },
                  "is_ldap": {
                    "type": "boolean"
                  },
                  "is_saml": {
                    "type": "boolean"
                  }
                }
              },
              "inc_id": {
                "type": "integer"
              },
              "inc_name": {
                "type": "string"
              },
              "inc_owner": {
                "type": "string"
              },
              "hits": {
                "type": "array"
              },
              "created": {
                "type": "integer"
              },
              "last_modified_time": {
                "type": "integer"
              },
              "last_modified_by": {
                "type": "object",
                "properties": {
                  "id": {
                    "type": "integer"
                  },
                  "type": {
                    "type": "string"
                  },
                  "name": {
                    "type": "string"
                  },
                  "display_name": {
                    "type": "string"
                  }
                }
              },
              "pending_sources": {
                "type": "array"
              },
              "perms": {
                "type": "object",
                "properties": {
                  "read": {
                    "type": "boolean"
                  },
                  "write": {
                    "type": "boolean"
                  },
                  "delete": {
                    "type": "boolean"
                  }
                }
              },
              "properties": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "name": {
                      "type": "string"
                    },
                    "value": {
                      "type": "string"
                    }
                  }
                }
              },
              "actions": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "integer"
                    },
                    "name": {
                      "type": "string"
                    },
                    "enabled": {
                      "type": "boolean"
                    }
                  }
                }
              },
              "playbooks": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "playbook_handle": {
                      "type": "string"
                    },
                    "display_name": {
                      "type": "string"
                    }
                  }
                }
              },
              "hash": {
                "type": "string"
              },
              "relating": {
                "type": "boolean"
              },
              "creator_principal": {
                "type": "object",
                "properties": {
                  "id": {
                    "type": "integer"
                  },
                  "type": {
                    "type": "string"
                  },
                  "name": {
                    "type": "string"
                  },
                  "display_name": {
                    "type": "string"
                  }
                }
              },
              "related_incident_count": {},
              "pending_scan_result": {
                "type": "boolean"
              },
              "global_info": {
                "type": "object",
                "properties": {
                  "id": {
                    "type": "integer"
                  },
                  "type": {
                    "type": "string"
                  },
                  "value": {
                    "type": "string"
                  },
                  "description": {},
                  "summary": {},
                  "creator": {
                    "type": "object",
                    "properties": {
                      "id": {
                        "type": "integer"
                      },
                      "type": {
                        "type": "string"
                      },
                      "name": {
                        "type": "string"
                      },
                      "display_name": {
                        "type": "string"
                      }
                    }
                  },
                  "created": {
                    "type": "integer"
                  },
                  "last_modified_by": {
                    "type": "object",
                    "properties": {
                      "id": {
                        "type": "integer"
                      },
                      "type": {
                        "type": "string"
                      },
                      "name": {
                        "type": "string"
                      },
                      "display_name": {
                        "type": "string"
                      }
                    }
                  },
                  "last_modified_time": {
                    "type": "integer"
                  },
                  "related_incident_count": {
                    "type": "integer"
                  },
                  "last_related_inc_id": {},
                  "last_related_inc_owner_handle": {},
                  "first_related_inc_id": {},
                  "first_related_inc_owner_handle": {},
                  "perms": {
                    "type": "object",
                    "properties": {
                      "write": {
                        "type": "boolean"
                      }
                    }
                  },
                  "first_associated_time": {
                    "type": "integer"
                  },
                  "last_associated_time": {
                    "type": "integer"
                  },
                  "properties": {},
                  "tags": {
                    "type": "array",
                    "items": {
                      "type": "object",
                      "properties": {
                        "tag_handle": {
                          "type": "string"
                        },
                        "value": {}
                      }
                    }
                  },
                  "version": {
                    "type": "integer"
                  },
                  "scan_option": {
                    "type": "string"
                  },
                  "relating_incidents": {
                    "type": "boolean"
                  },
                  "hit_threat_sources": {
                    "type": "array"
                  },
                  "relating": {
                    "type": "boolean"
                  },
                  "last_scan_hits": {
                    "type": "array"
                  }
                }
              },
              "ip": {
                "type": "object",
                "properties": {
                  "source": {
                    "type": "boolean"
                  },
                  "destination": {
                    "type": "boolean"
                  }
                }
              },
              "global_artifact": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "integer"
                    },
                    "type": {
                      "type": "string"
                    },
                    "value": {
                      "type": "string"
                    },
                    "description": {},
                    "summary": {},
                    "creator": {
                      "type": "object",
                      "properties": {
                        "id": {
                          "type": "integer"
                        },
                        "type": {
                          "type": "string"
                        },
                        "name": {
                          "type": "string"
                        },
                        "display_name": {
                          "type": "string"
                        }
                      }
                    },
                    "created": {
                      "type": "integer"
                    },
                    "last_modified_by": {
                      "type": "object",
                      "properties": {
                        "id": {
                          "type": "integer"
                        },
                        "type": {
                          "type": "string"
                        },
                        "name": {
                          "type": "string"
                        },
                        "display_name": {
                          "type": "string"
                        }
                      }
                    },
                    "last_modified_time": {
                      "type": "integer"
                    },
                    "related_incident_count": {
                      "type": "integer"
                    },
                    "last_related_inc_id": {},
                    "last_related_inc_owner_handle": {},
                    "first_related_inc_id": {},
                    "first_related_inc_owner_handle": {},
                    "perms": {
                      "type": "object",
                      "properties": {
                        "write": {
                          "type": "boolean"
                        }
                      }
                    },
                    "first_associated_time": {
                      "type": "integer"
                    },
                    "last_associated_time": {
                      "type": "integer"
                    },
                    "properties": {},
                    "tags": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "tag_handle": {
                            "type": "string"
                          },
                          "value": {}
                        }
                      }
                    },
                    "version": {
                      "type": "integer"
                    },
                    "scan_option": {
                      "type": "string"
                    },
                    "relating_incidents": {
                      "type": "boolean"
                    },
                    "hit_threat_sources": {
                      "type": "array"
                    },
                    "relating": {
                      "type": "boolean"
                    },
                    "last_scan_hits": {
                      "type": "array"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "raw": {},
    "inputs": {
      "type": "object",
      "properties": {
        "artifact_tag_values": {
          "type": "string"
        },
        "incident_id": {
          "type": "integer"
        },
        "artifact_type_values": {
          "type": "string"
        },
        "artifact_tag_method": {
          "type": "string"
        },
        "artifact_type_method": {
          "type": "string"
        },
        "artifact_include_incident_count": {
          "type": "boolean"
        },
        "artifact_value_method": {
          "type": "string"
        },
        "artifact_value": {
          "type": "string"
        }
      }
    },
    "metrics": {
      "type": "object",
      "properties": {
        "version": {
          "type": "string"
        },
        "package": {
          "type": "string"
        },
        "package_version": {
          "type": "string"
        },
        "host": {
          "type": "string"
        },
        "execution_time_ms": {
          "type": "integer"
        },
        "timestamp": {
          "type": "string"
        }
      }
    }
  }
}

=== TheIRGurus/Apps/fn_artifact_utils/payload_samples/artifact_utils_search_artifacts/output_json_example.json
{
  "version": 2.0,
  "success": true,
  "reason": null,
  "content": {
    "recordsTotal": 1,
    "recordsFiltered": 1,
    "data": [
      {
        "id": 1532,
        "type": "IP Address",
        "value": "10.10.10.10",
        "description": null,
        "attachment": null,
        "parent_id": null,
        "creator": {
          "id": 1,
          "fname": "John",
          "lname": "Doe",
          "display_name": "John Doe",
          "status": "A",
          "email": "john_doe@company.com",
          "locked": false,
          "password_changed": false,
          "is_external": false,
          "ui_theme": "verydarkmode",
          "is_ldap": false,
          "is_saml": false
        },
        "inc_id": 2325,
        "inc_name": "Sentinel Incident 1965 - First access credential added to Application or Service Principal where no credential was present",
        "inc_owner": "Tier 1",
        "hits": [],
        "created": 1683824680171,
        "last_modified_time": 1683844894105,
        "last_modified_by": {
          "id": 49,
          "type": "apikey",
          "name": "6bf8c47e-77a6-41ad-ad22-1004f7eee7cb",
          "display_name": "AppBuilder"
        },
        "pending_sources": [],
        "perms": {
          "read": true,
          "write": true,
          "delete": true
        },
        "properties": [
          {
            "name": "destination",
            "value": "false"
          },
          {
            "name": "source",
            "value": "false"
          }
        ],
        "actions": [
          {
            "id": 23,
            "name": "Update Data Table Row",
            "enabled": false
          },
          {
            "id": 96,
            "name": "Example: XML Transformation",
            "enabled": false
          },
          {
            "id": 21,
            "name": "Get Data Table Rows",
            "enabled": false
          },
          {
            "id": 91,
            "name": "Example: Shell Command",
            "enabled": false
          },
          {
            "id": 92,
            "name": "Example: String to Attachment",
            "enabled": false
          },
          {
            "id": 20,
            "name": "Get Data Table Row",
            "enabled": false
          },
          {
            "id": 17,
            "name": "Delete Data Table Rows",
            "enabled": false
          },
          {
            "id": 16,
            "name": "Delete Data Table Row",
            "enabled": false
          },
          {
            "id": 100,
            "name": "Add Row to Datatable",
            "enabled": false
          },
          {
            "id": 27,
            "name": "Defender Find Machine by DNS name",
            "enabled": false
          },
          {
            "id": 28,
            "name": "Defender Find Machines by File Hash",
            "enabled": false
          },
          {
            "id": 29,
            "name": "Defender Find Machines by Internal IP Address",
            "enabled": true
          },
          {
            "id": 30,
            "name": "Defender Get File Information",
            "enabled": false
          },
          {
            "id": 42,
            "name": "Defender Set Indicator",
            "enabled": true
          },
          {
            "id": 75,
            "name": "Example: (Artifact) Attachment to Base64",
            "enabled": false
          },
          {
            "id": 81,
            "name": "Example: Email Parsing (Artifact)",
            "enabled": false
          },
          {
            "id": 79,
            "name": "Example: Call REST API",
            "enabled": false
          },
          {
            "id": 76,
            "name": "Example: Artifact Hash",
            "enabled": false
          },
          {
            "id": 83,
            "name": "Example: Expand URL",
            "enabled": false
          },
          {
            "id": 84,
            "name": "Example: Extract SSL Certificate",
            "enabled": false
          },
          {
            "id": 87,
            "name": "Example: JSON2HTML",
            "enabled": false
          },
          {
            "id": 88,
            "name": "Example: Parse SSL Certificate",
            "enabled": false
          },
          {
            "id": 210,
            "name": "Example: LDAP Utilities: Remove User(s) from Group(s)",
            "enabled": false
          },
          {
            "id": 225,
            "name": "QRadar Move from Sample Blocked to Sample Suspected",
            "enabled": false
          },
          {
            "id": 145,
            "name": "Example: SEP - Get Endpoint Details for artifact",
            "enabled": false
          },
          {
            "id": 80,
            "name": "Example: Domain Distance",
            "enabled": false
          },
          {
            "id": 142,
            "name": "Example: SEP - Delete Hash from Blacklist",
            "enabled": false
          },
          {
            "id": 155,
            "name": "Example: SEP - Initiate EOC Scan for Artifact",
            "enabled": false
          },
          {
            "id": 213,
            "name": "Example: LDAP Utilities: Toggle Access",
            "enabled": false
          },
          {
            "id": 214,
            "name": "Example: LDAP Utilities: Update",
            "enabled": false
          },
          {
            "id": 221,
            "name": "Find All QRadar Reference Sets",
            "enabled": true
          },
          {
            "id": 222,
            "name": "Find in QRadar Reference Set",
            "enabled": true
          },
          {
            "id": 223,
            "name": "QRadar Add to Reference Set",
            "enabled": true
          },
          {
            "id": 191,
            "name": "Example: Exchange Online Get User Profile",
            "enabled": false
          },
          {
            "id": 224,
            "name": "QRadar Add to Reference Table",
            "enabled": true
          },
          {
            "id": 194,
            "name": "Example: Exchange Online Query Messages on Artifact",
            "enabled": false
          },
          {
            "id": 139,
            "name": "Example: SEP - Add Hash to Blacklist",
            "enabled": false
          },
          {
            "id": 205,
            "name": "Schedule a Rule/Playbook to Run - Artifact",
            "enabled": false
          },
          {
            "id": 267,
            "name": "Example: urlscan.io",
            "enabled": false
          },
          {
            "id": 209,
            "name": "Example: LDAP Utilities: Add User(s) to Group(s)",
            "enabled": false
          },
          {
            "id": 211,
            "name": "Example: LDAP Utilities: Search",
            "enabled": false
          },
          {
            "id": 212,
            "name": "Example: LDAP Utilities: Set Password",
            "enabled": false
          }
        ],
        "playbooks": [
          {
            "playbook_handle": "dig",
            "display_name": "Dig"
          },
          {
            "playbook_handle": "traceroute",
            "display_name": "Traceroute"
          },
          {
            "playbook_handle": "whois",
            "display_name": "Whois"
          },
          {
            "playbook_handle": "nmap_scan",
            "display_name": "NMAP Scan"
          },
          {
            "playbook_handle": "test",
            "display_name": "test"
          }
        ],
        "hash": "8a1f78cd1b0f77a54d47e45e8e70329d95286364646e1dab9cf6ad6b2a926bb1",
        "relating": true,
        "creator_principal": {
          "id": 1,
          "type": "user",
          "name": "john_doe@company.com",
          "display_name": "John Doe"
        },
        "related_incident_count": null,
        "pending_scan_result": false,
        "global_info": {
          "id": 537,
          "type": "IP Address",
          "value": "10.10.10.10",
          "description": null,
          "summary": null,
          "creator": {
            "id": 1,
            "type": "user",
            "name": "john_doe@company.com",
            "display_name": "John Doe"
          },
          "created": 1683824680171,
          "last_modified_by": {
            "id": 49,
            "type": "apikey",
            "name": "6bf8c47e-77a6-41ad-ad22-1004f7eee7cb",
            "display_name": "AppBuilder"
          },
          "last_modified_time": 1683874117659,
          "related_incident_count": 1,
          "last_related_inc_id": null,
          "last_related_inc_owner_handle": null,
          "first_related_inc_id": null,
          "first_related_inc_owner_handle": null,
          "perms": {
            "write": true
          },
          "first_associated_time": 1683824680171,
          "last_associated_time": 1683824680171,
          "properties": null,
          "tags": [
            {
              "tag_handle": "Internal",
              "value": null
            }
          ],
          "version": 13,
          "scan_option": "on",
          "relating_incidents": true,
          "hit_threat_sources": [],
          "relating": true,
          "last_scan_hits": []
        },
        "ip": {
          "source": false,
          "destination": false
        },
        "global_artifact": [
          {
            "id": 537,
            "type": "IP Address",
            "value": "10.10.10.10",
            "description": null,
            "summary": null,
            "creator": {
              "id": 1,
              "type": "user",
              "name": "john_doe@company.com",
              "display_name": "John Doe"
            },
            "created": 1683824680171,
            "last_modified_by": {
              "id": 49,
              "type": "apikey",
